### ISSUE TITLE
Doesn't work on my XEON 3680

### ISSUE THREAD

**Issue by AlexBrunetti** [amanjpro/zahak#128]
I'm testing the AMD 64 compile; the previous versions work fine.

uci
id name Zahak 7.0
id author Amanj
id EvalFile 2288800614
option name Ponder type check default false
option name Hash type spin default 128 min 1 max 24000
option name Book type check default false
option name Threads type spin default 1 min 1 max 6
option name EvalFile type string
option name BookFile type string
uciok
isready
readyok
position startpos
go wtime 30000
Exception 0xc000001d 0x0 0x0 0x4f9aff
PC=0x4f9aff

github.com/amanjpro/zahak/engine._quick_feed(0xc010394800, 0x80, 0xc000124200, 0x80, 0xc008335b3c)
        /home/runner/work/zahak/zahak/engine/nnue_instructions_amd64.s:250 +0x1f
github.com/amanjpro/zahak/engine.(*NetworkState).QuickFeed(0xc010384090, 0x0)
        /home/runner/work/zahak/zahak/engine/nnue_instructions_amd64.go:36 +0x98
github.com/amanjpro/zahak/engine.(*Position).Evaluate(0xc00004c2c0, 0xd29ddaaa4b272c47)
        /home/runner/work/zahak/zahak/engine/evaluation.go:50 +0x175
github.com/amanjpro/zahak/search.(*Engine).alphaBeta(0xc000136000, 0x7fff80010001, 0x1)
        /home/runner/work/zahak/zahak/search/search.go:283 +0x2da
github.com/amanjpro/zahak/search.(*Engine).aspirationWindow(0xc000136000, 0x18001, 0x64)
        /home/runner/work/zahak/zahak/search/search.go:166 +0x206
github.com/amanjpro/zahak/search.(*Engine).rootSearch(0xc000136000, 0x10164)
        /home/runner/work/zahak/zahak/search/search.go:123 +0x218
github.com/amanjpro/zahak/search.(*Engine).Search(0xc000136000, 0x64)
        /home/runner/work/zahak/zahak/search/search.go:40 +0x65
github.com/amanjpro/zahak/search.(*Runner).Search(0xc0081f6000, 0x7564)
        /home/runner/work/zahak/zahak/search/search.go:16 +0x145
created by github.com/amanjpro/zahak/uci.(*UCI).findMove
        /home/runner/work/zahak/zahak/uci/uci.go:241 +0x849

goroutine 1 [syscall, locked to thread]:
syscall.Syscall6(0x76fda740, 0x5, 0x3, 0xc00830c000, 0x1000, 0xc00000a07c, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/syscall_windows.go:343 +0xf2
syscall.ReadConsole(0x3, 0xc00830c000, 0x1000, 0xc00000a07c, 0x0, 0x5, 0x2)
        /opt/hostedtoolcache/go/1.16.8/x64/src/syscall/zsyscall_windows.go:982 +0xd5
internal/poll.(*FD).readConsole(0xc000110000, 0xc00830a000, 0x1000, 0x1000, 0x29640aa8, 0xc008200000, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/internal/poll/fd_windows.go:478 +0x23c
internal/poll.(*FD).Read(0xc000110000, 0xc00830a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/internal/poll/fd_windows.go:425 +0x137
os.(*File).read(...)
        /opt/hostedtoolcache/go/1.16.8/x64/src/os/file_posix.go:31
os.(*File).Read(0xc000006010, 0xc00830a000, 0x1000, 0x1000, 0x2030000, 0x6d8188, 0x4145d5)
        /opt/hostedtoolcache/go/1.16.8/x64/src/os/file.go:117 +0x85
bufio.(*Reader).fill(0xc008337d68)
        /opt/hostedtoolcache/go/1.16.8/x64/src/bufio/bufio.go:101 +0x10d
bufio.(*Reader).ReadSlice(0xc008337d68, 0x40dd0a, 0xc000051f40, 0x50, 0x48, 0x5388c0, 0xc000004001)
        /opt/hostedtoolcache/go/1.16.8/x64/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).collectFragments(0xc008337d68, 0x44400a, 0xc0083379c0, 0x464320, 0xc008337a08, 0xc008337a10, 0x10, 0xc00
0032000, 0x50ccc9, 0xc008337a98, ...)
        /opt/hostedtoolcache/go/1.16.8/x64/src/bufio/bufio.go:435 +0x85
bufio.(*Reader).ReadString(0xc008337d68, 0xc00004c20a, 0x6cff60, 0x0, 0x0, 0x1)
        /opt/hostedtoolcache/go/1.16.8/x64/src/bufio/bufio.go:483 +0x53
github.com/amanjpro/zahak/uci.(*UCI).Start(0xc00004c000)
        /home/runner/work/zahak/zahak/uci/uci.go:50 +0x1d3
main.main()
        /home/runner/work/zahak/zahak/zahak/main.go:89 +0x5d4
rax     0x80
rbx     0xc010394800
rcx     0x80
rdi     0xc010394800
rsi     0x80
rbp     0xc008335b40
rsp     0xc008335b08
r8      0xc008335b3c
r9      0x1
r10     0x8
r11     0x2
r12     0x2
r13     0x2
r14     0x9
r15     0xffffffffffffffff
rip     0x4f9aff
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by AlexBrunetti** [comment]
Doesn't apply, no avx cpu.
